.TH "runc-pause "8"" 
.nh
.ad l


.SH NAME
.PP
runc pause \- pause suspends all processes inside the container


.SH SYNOPSIS
.PP
runc pause \fB\fC<container\-id>\fR

.PP
Where "\fB\fC<container\-id>\fR" is the name for the instance of the container to be
paused.


.SH DESCRIPTION
.PP
The pause command suspends all processes in the instance of the container.
Use runc list to identify instances of containers and their current status.
