.TH "runc-exec "8"" 
.nh
.ad l


.SH NAME
.PP
runc exec \- execute new process inside the container


.SH SYNOPSIS
.PP
runc exec [command options] \fB\fC<container\-id>\fR \-\- \fB\fC<container command>\fR [args...]

.PP
Where "\fB\fC<container\-id>\fR" is the name for the instance of the container and
"\fB\fC<container command>\fR" is the command to be executed in the container.


.SH EXAMPLE
.PP
For example, if the container is configured to run the linux ps command the
following will output a list of processes running in the container:

.PP
.RS

.nf
   # runc exec <container\-id> ps

.fi
.RE


.SH OPTIONS
.PP
.RS

.nf
\-\-console value                          specify the pty slave path for use with the container
\-\-cwd value                              current working directory in the container
\-\-env value, \-e value                    set environment variables
\-\-tty, \-t                                allocate a pseudo\-TTY
\-\-user value, \-u value                   UID (format: <uid>[:<gid>])
\-\-additional\-gids value, \-g value        additional gids
\-\-process value, \-p value                path to the process.json
\-\-detach, \-d                             detach from the container's process
\-\-pid\-file value                         specify the file to write the process id to
\-\-process\-label value                    set the asm process label for the process commonly used with selinux
\-\-apparmor value                         set the apparmor profile for the process
\-\-no\-new\-privs                           set the no new privileges value for the process
\-\-cap value, \-c value                    add a capability to the bounding set for the process
\-\-no\-subreaper                           disable the use of the subreaper used to reap reparented processes
\-\-preserve\-fds value                     pass N additional file descriptors to the container (stdio + $LISTEN\_FDS + N in total) (default: 0)

.fi
.RE
