.TH "runc-kill "8"" 
.nh
.ad l


.SH NAME
.PP
runc kill \- kill sends the specified signal (default: SIGTERM) to the container's init process


.SH SYNOPSIS
.PP
runc kill [command options] \fB\fC<container\-id>\fR \fB\fC<signal>\fR

.PP
Where "\fB\fC<container\-id>\fR" is the name for the instance of the container and
"\fB\fC<signal>\fR" is the signal to be sent to the init process.


.SH OPTIONS
.PP
.RS

.nf
\-\-all, \-a  send the specified signal to all processes inside the container

.fi
.RE


.SH EXAMPLE
.PP
For example, if the container id is "ubuntu01" the following will send a "KILL"
signal to the init process of the "ubuntu01" container:

.PP
.RS

.nf
   # runc kill ubuntu01 KILL

.fi
.RE
