.TH "runc-events "8"" 
.nh
.ad l


.SH NAME
.PP
runc events \- display container events such as OOM notifications, cpu, memory, and IO usage statistics


.SH SYNOPSIS
.PP
runc events [command options] \fB\fC<container\-id>\fR

.PP
Where "\fB\fC<container\-id>\fR" is the name for the instance of the container.


.SH DESCRIPTION
.PP
The events command displays information about the container. By default the
information is displayed once every 5 seconds.


.SH OPTIONS
.PP
.RS

.nf
\-\-interval value     set the stats collection interval (default: 5s)
\-\-stats              display the container's stats then exit

.fi
.RE
