.TH "runc-ps "8"" 
.nh
.ad l


.SH NAME
.PP
runc ps \- ps displays the processes running inside a container


.SH SYNOPSIS
.PP
runc ps [command options] \fB\fC<container\-id>\fR [ps options]


.SH OPTIONS
.PP
.RS

.nf
\-\-format value, \-f value     select one of: table(default) or json

.fi
.RE

.PP
The default format is table. The following will output the processes of a container
in json format:

.PP
.RS

.nf
# runc ps \-f json <container\-id>

.fi
.RE
