.TH "runc-list "8"" 
.nh
.ad l


.SH NAME
.PP
runc list \- lists containers started by runc with the given root


.SH SYNOPSIS
.PP
runc list [command options]


.SH EXAMPLE
.PP
Where the given root is specified via the global option "\-\-root"
(default: "/run/runc").

.PP
To list containers created via the default "\-\-root":
       # runc list

.PP
To list containers created using a non\-default value for "\-\-root":
       # runc \-\-root value list


.SH OPTIONS
.PP
.RS

.nf
\-\-format value, \-f value     select one of: table or json (default: "table")
\-\-quiet, \-q                  display only container IDs

.fi
.RE
