.TH "runc-state "8"" 
.nh
.ad l


.SH NAME
.PP
runc state \- output the state of a container


.SH SYNOPSIS
.PP
runc state \fB\fC<container\-id>\fR

.PP
Where "\fB\fC<container\-id>\fR" is your name for the instance of the container.


.SH DESCRIPTION
.PP
The state command outputs current state information for the
instance of a container.
