.TH "runc-resume "8"" 
.nh
.ad l


.SH NAME
.PP
runc resume \- resumes all processes that have been previously paused


.SH SYNOPSIS
.PP
runc resume \fB\fC<container\-id>\fR

.PP
Where "\fB\fC<container\-id>\fR" is the name for the instance of the container to be
resumed.


.SH DESCRIPTION
.PP
The resume command resumes all processes in the instance of the container.
Use runc list to identify instances of containers and their current status.
