.TH "runc-delete "8"" 
.nh
.ad l


.SH NAME
.PP
runc delete \- delete any resources held by the container often used with detached container


.SH SYNOPSIS
.PP
runc delete [command options] \fB\fC<container\-id>\fR

.PP
Where "\fB\fC<container\-id>\fR" is the name for the instance of the container.


.SH OPTIONS
.PP
.RS

.nf
\-\-force, \-f     Forcibly deletes the container if it is still running (uses SIGKILL)

.fi
.RE


.SH EXAMPLE
.PP
For example, if the container id is "ubuntu01" and runc list currently shows the
status of "ubuntu01" as "stopped" the following will delete resources held for
"ubuntu01" removing "ubuntu01" from the runc list of containers:

.PP
.RS

.nf
   # runc delete ubuntu01

.fi
.RE
