.TH MKBOOTDISK 8 "Tue Mar 31 1998"
.UC 4
.SH NAME
mkbootdisk \- creates a stand-alone boot floppy for the running system
.SH SYNOPSIS
\fBmkbootdisk\fR [\fB--version\fR] [\fB--noprompt\fR] [\fB--verbose\fR] 
           [\fB--device \fIdevicefile\fR] [\fB--size \fIsize\fR]
           [\fB--kernelargs \fI<args>\fR] [\fB--iso\fR] \fIkernel\fR

.SH DESCRIPTION
\fBmkbootdisk\fR creates a boot floppy appropriate for the running system. The
boot disk is entirely self-contained, and includes an initial ramdisk image
which loads any necessary SCSI modules for the system. The created boot 
disk looks for the root filesystem on the device suggested by /etc/fstab.
The only required argument is the kernel version to put onto the boot
floppy.

.SH OPTIONS
.TP
\fB-\-device \fIdevicefile\fR
The boot image is created on \fIdevicefile\fR. If \fB--device\fR is not
specified, /dev/fd0 is used. If \fIdevicefile\fR does not exist 
\fBmkinitrd\fR creates a 1.44Mb floppy image using \fIdevicefile\fR as
the filename.

.TP
\fB-\-noprompt\fR
Normally, \fBmkbootdisk\fR instructs the user to insert a floppy and
waits for confirmation before continuing. If \fB-\-noprompt\fR is 
specified, no prompt is displayed.

.TP
\fB-\-verbose\fR
Instructs \fBmkbootdisk\fR to talk about what it's doing as it's doing
it. Normally, there is no output from \fBmkbootdisk\fR.

.TP
\fB-\-iso\fR
Instructs \fBmkbootdisk\fR to make a bootable ISO image as \fIdevicefile\fR.

.TP
\fB-\-version\fR
Displays the version of \fBmkbootdisk\fR and exits.

.TP
\fB-\-kernelargs \fIargs\fR
Adds \fIargs\fR to the arguments appended on the kernel command line. If this
is not specified \fBmkbootdisk\fR uses \fBgrubby\fR to parse the arguments
for the default kernel from \fBgrub.conf\fR, if possible.

.TP
\fB-\-size \fIsize\fR
Uses \fIsize\fR (in kilobytes) as the size of the image to use for the boot
disk.  If this is not specified, \fBmkbootdisk\fR will assume a standard 
1.44Mb floppy device.

.SH "SEE ALSO"
.BR grubby (8)
.BR dracut (8)

.SH AUTHOR
.nf
Erik Troan <ewt@redhat.com>
.fi
