'\" t
.\"     Title: trace-cmd-stop
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 02/03/2019
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "TRACE\-CMD\-STOP" "1" "02/03/2019" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
trace-cmd-stop \- stop the Ftrace Linux kernel tracer from writing to the ring buffer\&.
.SH "SYNOPSIS"
.sp
\fBtrace\-cmd stop\fR [\fIOPTIONS\fR]
.SH "DESCRIPTION"
.sp
The trace\-cmd(1) stop is a complement to \fItrace\-cmd\-start(1)\fR\&. This will disable Ftrace from writing to the ring buffer\&. This does not stop the overhead that the tracing may incur\&. Only the updating of the ring buffer is disabled, the Ftrace tracing may still be inducing overhead\&.
.sp
After stopping the trace, the \fItrace\-cmd\-extract(1)\fR may strip out the data from the ring buffer and create a trace\&.dat file\&. The Ftrace pseudo file system may also be examined\&.
.sp
To disable the tracing completely to remove the overhead it causes, use \fItrace\-cmd\-reset(1)\fR\&. But after a reset is performed, the data that has been recorded is lost\&.
.SH "OPTIONS"
.PP
\fB\-B\fR \fIbuffer\-name\fR
.RS 4
If the kernel supports multiple buffers, this will stop the trace for only the given buffer\&. It does not affect any other buffer\&. This may be used multiple times to specify different buffers\&. When this option is used, the top level instance will not be stopped unless
\fB\-t\fR
is given\&.
.RE
.PP
\fB\-a\fR
.RS 4
Stop the trace for all existing buffer instances\&. When this option is used, the top level instance will not be stopped unless
\fB\-t\fR
is given\&.
.RE
.PP
\fB\-t\fR
.RS 4
Stops the top level instance buffer\&. Without the
\fB\-B\fR
or
\fB\-a\fR
option this is the same as the default\&. But if
\fB\-B\fR
or
\fB\-a\fR
is used, this is required if the top level instance buffer should also be stopped\&.
.RE
.SH "SEE ALSO"
.sp
trace\-cmd(1), trace\-cmd\-record(1), trace\-cmd\-report(1), trace\-cmd\-start(1), trace\-cmd\-extract(1), trace\-cmd\-reset(1), trace\-cmd\-split(1), trace\-cmd\-list(1), trace\-cmd\-listen(1)
.SH "AUTHOR"
.sp
Written by Steven Rostedt, <\m[blue]\fBrostedt@goodmis\&.org\fR\m[]\&\s-2\u[1]\d\s+2>
.SH "RESOURCES"
.sp
git://git\&.kernel\&.org/pub/scm/linux/kernel/git/rostedt/trace\-cmd\&.git
.SH "COPYING"
.sp
Copyright (C) 2010 Red Hat, Inc\&. Free use of this software is granted under the terms of the GNU Public License (GPL)\&.
.SH "NOTES"
.IP " 1." 4
rostedt@goodmis.org
.RS 4
\%mailto:rostedt@goodmis.org
.RE
