'\" t
.\"     Title: abrt-auto-reporting
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 09/24/2020
.\"    Manual: ABRT Manual
.\"    Source: abrt 2.14.4
.\"  Language: English
.\"
.TH "ABRT\-AUTO\-REPORTIN" "1" "09/24/2020" "abrt 2\&.14\&.4" "ABRT Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
abrt-auto-reporting \- Get or modify the auto reporting option values
.SH "SYNOPSIS"
.sp
\fIabrt\-auto\-reporting\fR [\-v] [ enabled | yes | 1 | on | disabled | no | 0 | off ]
.SH "DESCRIPTION"
.sp
Reads the configuration from abrt\&.conf and saves the changes to the same file\&.
.sp
The changes will take effect immediately without necessity to restart any ABRT process and will be persistent\&.
.PP
\fIdisabled\fR
.RS 4
User have to report the detect problems manually
.RE
.PP
\fIenabled\fR
.RS 4
ABRT uploads an uReport which was generated for a detected problem immediately after the detection phase\&.
.RE
.SS "uReport description"
.sp
ABRT supports uReports for four types of crashes: crashes of C/C++ programs that result in a core dump, uncaught Python exceptions, uncaught Java exceptions and kernel oopses\&.
.sp
Each uReport generally contains a stack trace, or multiple stack traces in the case of multi\-threaded C/C++ and Java programs\&. The stack trace only describes the call stack of the program at the time of the crash and does not contain contents of any variables\&.
.sp
Every uReport also contains identification of the operating system, versions of the RPM packages involved in the crash, and whether the program ran under a root user\&.
.sp
There are also items specific to each crash type:
.PP
C/C++ crashes
.RS 4
these are path to the executable and signal delivered to the program,
.RE
.PP
Python exceptions
.RS 4
there is the type of the exception (without the error message, which may contain sensitive data),
.RE
.PP
for kernel oopses
.RS 4
these are list of loaded kernel modules, list of taint flags, and full text of the kernel oops\&.
.RE
.sp
\fIWarning\fR: The full text of a kernel oops might contain information like the identification of the host hardware type\&. You should disable the autoreporting feature if you do not want to share this information with Red Hat\&.
.SH "OPTIONS"
.PP
\-v, \-\-verbose
.RS 4
Be more verbose\&. Can be given multiple times\&.
.RE
.SH "SEE ALSO"
.sp
abrt\&.conf(5)
.SH "AUTHORS"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ABRT team
.RE
