'\" t
.\"     Title: abrt-action-analyze-xorg
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 09/24/2020
.\"    Manual: ABRT Manual
.\"    Source: abrt 2.14.4
.\"  Language: English
.\"
.TH "ABRT\-ACTION\-ANALYZ" "1" "09/24/2020" "abrt 2\&.14\&.4" "ABRT Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
abrt-action-analyze-xorg \- Calculate and save UUID and duplicate hash for a problem data directory DIR with Xorg backtrace\&.
.SH "SYNOPSIS"
.sp
\fIabrt\-action\-analyze\-xorg\fR [\-v] [\-d DIR]
.SH "DESCRIPTION"
.sp
The tool reads the file named \fIXorg\&.0\&.log\fR and checks if any black listed module was loaded\&. If so, \fInot\-reportable\fR file is created with an appropriate explanation text\&. If no black listed module was loaded, the tool reads the file named \fIbacktrace\fR from a problem data directory record and generates a duplication hash and a universally unique identifier (UUID)\&. Then it saves this data as new elements \fIduphash\fR and \fIuuid\fR\&.
.SS "Integration with ABRT events"
.sp
\fIabrt\-action\-analyze\-xorg\fR can be used to generate the duplication hash of a newly discovered Xorg backtraces\&.
.sp
.if n \{\
.RS 4
.\}
.nf
EVENT=post\-create analyzer=Xorg   abrt\-action\-analyze\-xorg
.fi
.if n \{\
.RE
.\}
.SH "OPTIONS"
.PP
\-d DIR
.RS 4
Path to a problem directory\&. Current working directory is used when this option is not provided\&.
.RE
.PP
\-v
.RS 4
Be more verbose\&. Can be given multiple times\&.
.RE
.SH "FILES"
.PP
/etc/abrt/plugins/xorg\&.conf
.RS 4
Configuration file for ABRT\(cqs tools which work with Xorg crashes
.RE
.SH "SEE ALSO"
.sp
abrt\-dump\-journal\-xorg(1) abrt\-xorg\&.conf(5)
.SH "AUTHORS"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ABRT team
.RE
