'\" t
.\"     Title: abrt-server
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 09/24/2020
.\"    Manual: ABRT Manual
.\"    Source: abrt 2.14.4
.\"  Language: English
.\"
.TH "ABRT\-SERVER" "1" "09/24/2020" "abrt 2\&.14\&.4" "ABRT Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
abrt-server \- Unix socket for ABRT\&.
.SH "SYNOPSIS"
.sp
\fIabrt\-server\fR [\-u UID] [\-spv[v]\&...]
.SH "DESCRIPTION"
.sp
\fIabrt\-server\fR is executed by abrtd daemon to handle socket connections\&. Every application in system is able to invoke creation of a new problem directory by following the communication protocol (described below in section \fIPROTOCOL\fR)\&.
.SH "OPTIONS"
.PP
\-u UID
.RS 4
Use UID as client uid
.RE
.PP
\-s
.RS 4
Log to system log\&.
.RE
.PP
\-p
.RS 4
Add program names to log\&.
.RE
.PP
\-v
.RS 4
Log more detailed debugging information\&.
.RE
.SH "PROTOCOL"
.sp
Initializing new dump: connect to UNIX domain socket /var/run/abrt\&.socket
.sp
Providing data (writing data to the socket):
.sp
.if n \{\
.RS 4
.\}
.nf
\-> "POST / HTTP/1\&.1\er\en"
\-> "\er\en"
\-> "type=string\e0"
   string, maximum length 100 bytes
\-> "reason=string\e0"
   string, maximum length 512 bytes
\-> "pid=number\e0"
   number, 0 \- PID_MAX (/proc/sys/kernel/pid_max)
\-> "executable=string\e0"
   string, maximum length ~MAX_PATH
\-> "backtrace=string\e0"
   string, maximum length 1 MB
\-> (close writing half of the socket)
<\- "HTTP/1\&.1 201 \er\en"
<\- "\er\en"
.fi
.if n \{\
.RE
.\}
.sp
Deleting problem directory:
.sp
.if n \{\
.RS 4
.\}
.nf
\-> "DELETE <directory_name> HTTP/1\&.1\er\en"
\-> "\er\en"
\-> (close writing half of the socket)
<\- "HTTP/1\&.1 200 \er\en"
<\- "\er\en"
.fi
.if n \{\
.RE
.\}
.SH "AUTHORS"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ABRT team
.RE
