'\" t
.\"     Title: abrt.conf
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 09/24/2020
.\"    Manual: ABRT Manual
.\"    Source: abrt 2.14.4
.\"  Language: English
.\"
.TH "ABRT\&.CONF" "5" "09/24/2020" "abrt 2\&.14\&.4" "ABRT Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
abrt.conf \- Configuration file for ABRT\&.
.SH "SYNOPSIS"
.sp
/etc/abrt/abrt\&.conf
.SH "DESCRIPTION"
.sp
ABRT is a daemon that watches for application crashes\&. When a crash occurs, it collects the problem data and takes action according to its configuration\&. This document describes ABRT\(cqs configuration file\&.
.sp
The configuration file consists of items in the format "Option = Value"\&. A description of each item follows:
.PP
\fBDumpLocation = \fR\fB\fIdirectory\fR\fR
.RS 4
The directory where ABRT should store coredumps and other files which are needed for reporting\&.

Default is
\fI/var/spool/abrt\fR\&.
.RE
.PP
\fBMaxCrashReportsSize = \fR\fB\fInumber\fR\fR
.RS 4
The maximum disk space (specified in MiB) that ABRT will use for all the crash dumps\&. Value of 0 means "unlimited space"\&.

Default is 5000\&.
.RE
.PP
\fBWatchCrashdumpArchiveDir = \fR\fB\fIdirectory\fR\fR
.RS 4
The daemon will watch this directory and call
\fIabrt\-handle\-upload\fR
on files which appear there\&. This is used to auto\-unpack crashdump tarballs uploaded via FTP, SCP, etc\&.

Note: The directory must exist and be writable for
\fIabrtd\fR\&. It will not be created automatically\&.

Example: /var/spool/abrt\-upload

Default is none, hence the feature is disabled\&.
.RE
.PP
\fBDeleteUploaded = \fR\fB\fIyes/no\fR\fR
.RS 4
The daemon will delete an uploaded crashdump archive after an atempt to unpack it\&. An archive will be delete whether unpacking finishes successfully or not\&.

If you decide to enable this, you have to tweak the SELinux policy:
# setsebool \-P abrt_anon_write 1\&.

Default value is
\fIno\fR\&.
.RE
.PP
\fBDebugLevel = \fR\fB\fI0\-100\fR\fR
.RS 4
Allows ABRT tools to detect problems in ABRT itself\&. By increasing the value you can force ABRT to detect, process and report problems in ABRT\&. You have to bear in mind that ABRT might fall into an infinite loop when handling problems caused by itself\&.

Default is 0 (non debug mode)\&.
.RE
.PP
\fBAutoreportingEnabled = \fR\fB\fIyes/no\fR\fR
.RS 4
Enables automatic execution of the event configured in
\fIAutoreportingEvent\fR
option\&.

Default is
\fIno\fR\&.
.RE
.PP
\fBAutoreportingEvent = \fR\fB\fIevent\fR\fR
.RS 4
A name of event which is run automatically after problem\(cqs detection\&. The event should perform some fast analysis and exit with 70 if the problem is known\&.

Default is
\fIreport_uReport\fR\&.
.RE
.PP
\fBShortenedReporting = \fR\fB\fIyes/no\fR\fR
.RS 4
Enables shortened GUI reporting where the reporting is interrupted after
\fIAutoreportingEvent\fR
is done\&.

Default is
\fIyes\fR
if application is running in a GNOME desktop session; otherwise it\(cqs
\fIno\fR\&.
.RE
.PP
\fBExploreChroots = \fR\fB\fIyes/no\fR\fR
.RS 4
Enables various features exploring process\(cqs root directories if they differ from the default root directory\&. The following list includes examples of enabled features:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
query the RPM database in the process\(cqs root directory,
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
save files like
/etc/os\-release
from the process\(cqs root directory\&.
.RE
.sp
This feature is disabled by default because it might be used by a local user to steal your data\&.
.sp
Caution: THIS FEATURE MIGHT BE USED BY A LOCAL USER TO STEAL YOUR DATA BY ARRANGING A SPECIAL ROOT DIRECTORY IN USER MOUNT NAMESPACE\&.
.sp
Default is
\fIno\fR\&.
.RE
.SH "FILES"
.sp
/etc/abrt/abrt\&.conf
.SH "SEE ALSO"
.sp
abrtd(8) abrt\-action\-save\-package\-data\&.conf(5) abrt\-handle\-upload(1)
.SH "AUTHORS"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ABRT team
.RE
