'\" t
.\"     Title: trace-cmd-list
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 02/03/2019
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "TRACE\-CMD\-LIST" "1" "02/03/2019" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
trace-cmd-list \- list available plugins, events or options for Ftrace\&.
.SH "SYNOPSIS"
.sp
\fBtrace\-cmd list\fR [\fIOPTIONS\fR]
.SH "DESCRIPTION"
.sp
The trace\-cmd(1) list displays the available plugins, events or Ftrace options that are configured on the current machine\&. If no option is given, then it lists all plugins, events and Ftrace options to standard output\&.
.SH "OPTIONS"
.PP
\fB\-e\fR [\fIregex\fR]
.RS 4
This option will list the available events that are enabled on the local system\&.
.sp
.if n \{\
.RS 4
.\}
.nf
It takes an optional argument that uses \*(Aqregcomp(3)\*(Aq expressions to seach\&.
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
trace\-cmd list \-e \*(Aq^sys\&.*\*(Aq
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fB\-F\fR
.RS 4
Used with
\fB\-e\fR
\fIregex\fR
to show those events formats\&.
.RE
.PP
\fB\-l\fR
.RS 4
Used with
\fB\-e\fR
\fIregex\fR
to show those events filters\&.
.RE
.PP
\fB\-R\fR
.RS 4
Used with
\fB\-e\fR
\fIregex\fR
to show those events triggers\&.
.RE
.PP
\fB\-t\fR
.RS 4
This option will list the available tracers that are enabled on the local system\&.
.RE
.PP
\fB\-p\fR
.RS 4
Same as
\fB\-t\fR
and only for legacy purposes\&.
.RE
.PP
\fB\-o\fR
.RS 4
This option will list the available Ftrace options that are configured on the local system\&.
.RE
.PP
\fB\-f\fR [\fIregex\fR]
.RS 4
This option will list the available filter functions\&. These are the list of functions on the system that you can trace, or filter on\&. It takes an optional argument that uses
\fIregcomp(3)\fR
expressions to seach\&.
.sp
.if n \{\
.RS 4
.\}
.nf
trace\-cmd list \-f \*(Aq^sched\&.*\*(Aq
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fB\-P\fR
.RS 4
List the plugin files that get loaded on trace\-cmd report\&.
.RE
.PP
\fB\-O\fR
.RS 4
List plugin options that can be used by trace\-cmd report
\fB\-O\fR
option\&.
.RE
.PP
\fB\-B\fR
.RS 4
List defined buffer instances (sub buffers)\&.
.RE
.PP
\fB\-C\fR
.RS 4
List defined clocks that can be used with trace\-cmd record \-C\&. The one in brackets ([]) is the active clock\&.
.RE
.SH "SEE ALSO"
.sp
trace\-cmd(1), trace\-cmd\-record(1), trace\-cmd\-report(1), trace\-cmd\-start(1), trace\-cmd\-stop(1), trace\-cmd\-extract(1), trace\-cmd\-reset(1), trace\-cmd\-split(1), trace\-cmd\-listen(1)
.SH "AUTHOR"
.sp
Written by Steven Rostedt, <\m[blue]\fBrostedt@goodmis\&.org\fR\m[]\&\s-2\u[1]\d\s+2>
.SH "RESOURCES"
.sp
git://git\&.kernel\&.org/pub/scm/linux/kernel/git/rostedt/trace\-cmd\&.git
.SH "COPYING"
.sp
Copyright (C) 2010 Red Hat, Inc\&. Free use of this software is granted under the terms of the GNU Public License (GPL)\&.
.SH "NOTES"
.IP " 1." 4
rostedt@goodmis.org
.RS 4
\%mailto:rostedt@goodmis.org
.RE
