'\" t
.\"     Title: trace-cmd-extract
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 02/03/2019
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "TRACE\-CMD\-EXTRACT" "1" "02/03/2019" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
trace-cmd-extract \- extract out the data from the Ftrace Linux tracer\&.
.SH "SYNOPSIS"
.sp
\fBtrace\-cmd extract [\fR\fB\fIOPTIONS\fR\fR\fB]\fR
.SH "DESCRIPTION"
.sp
The trace\-cmd(1) extract is usually used after \fItrace\-cmd\-start(1)\fR and \fItrace\-cmd\-stop(1)\fR\&. It can be used after the Ftrace tracer has been started manually through the Ftrace pseudo file system\&.
.sp
The extract command creates a trace\&.dat file that can be used by \fItrace\-cmd\-report(1)\fR to read from\&. It reads the kernel internal ring buffer to produce the trace\&.dat file\&.
.SH "OPTIONS"
.PP
\fB\-p\fR \fIplugin\fR
.RS 4
Although
\fBextract\fR
does not start any traces, some of the plugins require just reading the output in ASCII format\&. These are the latency tracers, since the latency tracers have a separate internal buffer\&. The plugin option is therefore only necessary for the
\fIwakeup\fR,
\fIwakeup\-rt\fR,
\fIirqsoff\fR,
\fIpreemptoff\fR
and
\fIpreemptirqsoff\fR
plugins\&.
.sp
.if n \{\
.RS 4
.\}
.nf
With out this option, the extract command will extract from the internal
Ftrace buffers\&.
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fB\-O\fR \fIoption\fR
.RS 4
If a latency tracer is being extracted, and the
\fB\-p\fR
option is used, then there are some Ftrace options that can change the format\&. This will update those options before extracting\&. To see the list of options see
\fItrace\-cmd\-list\fR\&. To enable an option, write its name, to disable the option append the characters
\fIno\fR
to it\&. For example:
\fInoprint\-parent\fR
will disable the
\fIprint\-parent\fR
option that prints the parent function in printing a function event\&.
.RE
.PP
\fB\-o\fR \fIoutputfile\fR
.RS 4
By default, the extract command will create a
\fItrace\&.dat\fR
file\&. This option will change where the file is written to\&.
.RE
.PP
\fB\-s\fR
.RS 4
Extract from the snapshot buffer (if the kernel supports it)\&.
.RE
.PP
\fB\-\-date\fR
.RS 4
This is the same as the trace\-cmd\-record(1) \-\-date option, but it does cause the extract routine to disable all tracing\&. That is, the end of the extract will perform something similar to trace\-cmd\-reset(1)\&.
.RE
.PP
\fB\-B\fR \fIbuffer\-name\fR
.RS 4
If the kernel supports multiple buffers, this will extract the trace for only the given buffer\&. It does not affect any other buffer\&. This may be used multiple times to specify different buffers\&. When this option is used, the top level instance will not be extracted unless
\fB\-t\fR
is given\&.
.RE
.PP
\fB\-a\fR
.RS 4
Extract all existing buffer instances\&. When this option is used, the top level instance will not be extracted unless
\fB\-t\fR
is given\&.
.RE
.PP
\fB\-t\fR
.RS 4
Extracts the top level instance buffer\&. Without the
\fB\-B\fR
or
\fB\-a\fR
option this is the same as the default\&. But if
\fB\-B\fR
or
\fB\-a\fR
is used, this is required if the top level instance buffer should also be extracted\&.
.RE
.SH "SEE ALSO"
.sp
trace\-cmd(1), trace\-cmd\-record(1), trace\-cmd\-report(1), trace\-cmd\-start(1), trace\-cmd\-stop(1), trace\-cmd\-reset(1), trace\-cmd\-split(1), trace\-cmd\-list(1), trace\-cmd\-listen(1)
.SH "AUTHOR"
.sp
Written by Steven Rostedt, <\m[blue]\fBrostedt@goodmis\&.org\fR\m[]\&\s-2\u[1]\d\s+2>
.SH "RESOURCES"
.sp
git://git\&.kernel\&.org/pub/scm/linux/kernel/git/rostedt/trace\-cmd\&.git
.SH "COPYING"
.sp
Copyright (C) 2010 Red Hat, Inc\&. Free use of this software is granted under the terms of the GNU Public License (GPL)\&.
.SH "NOTES"
.IP " 1." 4
rostedt@goodmis.org
.RS 4
\%mailto:rostedt@goodmis.org
.RE
