'\" t
.\"     Title: trace-cmd-stat
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 02/03/2019
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "TRACE\-CMD\-STAT" "1" "02/03/2019" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
trace-cmd-stat \- show the status of the tracing (ftrace) system
.SH "SYNOPSIS"
.sp
\fBtrace\-cmd stat\fR
.SH "DESCRIPTION"
.sp
The trace\-cmd(1) stat displays the various status of the tracing (ftrace) system\&. The status that it shows is:
.sp
\fBTracer:\fR if one of the tracers (like function_graph) is active\&. Otherwise nothing is displayed\&.
.sp
\fBEvents:\fR Lists the events that are enable\&.
.sp
\fBEvent filters:\fR Shows any filters that are set for any events
.sp
\fBFunction filters:\fR Shows any filters for the function tracers
.sp
\fBGraph functions:\fR Shows any functions that the function graph tracer should graph
.sp
\fBBuffers:\fR Shows the trace buffer size if they have been expanded\&. By default, tracing buffers are in a compressed format until they are used\&. If they are compressed, the buffer display will not be shown\&.
.sp
\fBTrace clock:\fR If the tracing clock is anything other than the default "local" it will be displayed\&.
.sp
\fBTrace CPU mask:\fR If not all available CPUs are in the tracing CPU mask, then the tracing CPU mask will be displayed\&.
.sp
\fBTrace max latency:\fR Shows the value of the trace max latency if it is other than zero\&.
.sp
\fBKprobes:\fR Shows any kprobes that are defined for tracing\&.
.sp
\fBUprobes:\fR Shows any uprobes that are defined for tracing\&.
.SH "SEE ALSO"
.sp
trace\-cmd(1), trace\-cmd\-record(1), trace\-cmd\-report(1), trace\-cmd\-start(1), trace\-cmd\-stop(1), trace\-cmd\-extract(1), trace\-cmd\-reset(1), trace\-cmd\-split(1), trace\-cmd\-listen(1)
.SH "AUTHOR"
.sp
Written by Steven Rostedt, <\m[blue]\fBrostedt@goodmis\&.org\fR\m[]\&\s-2\u[1]\d\s+2>
.SH "RESOURCES"
.sp
git://git\&.kernel\&.org/pub/scm/linux/kernel/git/rostedt/trace\-cmd\&.git
.SH "COPYING"
.sp
Copyright (C) 2014 Red Hat, Inc\&. Free use of this software is granted under the terms of the GNU Public License (GPL)\&.
.SH "NOTES"
.IP " 1." 4
rostedt@goodmis.org
.RS 4
\%mailto:rostedt@goodmis.org
.RE
