'\" t
.\"     Title: trace-cmd-check_events
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 02/03/2019
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "TRACE\-CMD\-CHECK_EV" "1" "02/03/2019" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
trace-cmd-check-events \- parse the event formats on local system
.SH "SYNOPSIS"
.sp
\fBtrace\-cmd check\-events\fR [\fIOPTIONS\fR]
.SH "DESCRIPTION"
.sp
The trace\-cmd(1) check\-events parses format strings for all the events on the local system\&. It returns whether all the format strings can be parsed correctly\&. It will load plugins unless specified otherwise\&.
.sp
This is useful to check for any trace event format strings which may contain some internal kernel function references which cannot be decoded outside of the kernel\&. This may mean that either the unparsed format strings of the trace events need to be changed or that a plugin needs to be created to parse them\&.
.SH "OPTIONS"
.sp
\fB\-N\fR \- Don\(cqt load plugins
.SH "SEE ALSO"
.sp
trace\-cmd(1), trace\-cmd\-record(1), trace\-cmd\-report(1), trace\-cmd\-stop(1), trace\-cmd\-extract(1), trace\-cmd\-reset(1), trace\-cmd\-split(1), trace\-cmd\-list(1), trace\-cmd\-listen(1), trace\-cmd\-start(1)
.SH "AUTHOR"
.sp
Written by Vaibhav Nagarnaik, <\m[blue]\fBvnagarnaik@google\&.com\fR\m[]\&\s-2\u[1]\d\s+2>
.SH "RESOURCES"
.sp
git://git\&.kernel\&.org/pub/scm/linux/kernel/git/rostedt/trace\-cmd\&.git
.SH "COPYING"
.sp
Copyright (C) 2011 Google, Inc\&. Free use of this software is granted under the terms of the GNU Public License (GPL)\&.
.SH "NOTES"
.IP " 1." 4
vnagarnaik@google.com
.RS 4
\%mailto:vnagarnaik@google.com
.RE
