'\" t
.\"     Title: trace-cmd-listen
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 02/03/2019
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "TRACE\-CMD\-LISTEN" "1" "02/03/2019" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
trace-cmd-listen \- listen for incoming connection to record tracing\&.
.SH "SYNOPSIS"
.sp
\fBtrace\-cmd listen\fR \-p \fIport\fR [\fIOPTIONS\fR]
.SH "DESCRIPTION"
.sp
The trace\-cmd(1) listen sets up a port to listen to waiting for connections from other hosts that run \fItrace\-cmd\-record(1)\fR with the \fB\-N\fR option\&. When a connection is made, and the remote host sends data, it will create a file called \fItrace\&.HOST:PORT\&.dat\fR\&. Where HOST is the name of the remote host, and PORT is the port that the remote host used to connect with\&.
.SH "OPTIONS"
.PP
\fB\-p\fR \fIport\fR
.RS 4
This option will specify the port to listen to\&.
.RE
.PP
\fB\-D\fR
.RS 4
This options causes trace\-cmd listen to go into a daemon mode and run in the background\&.
.RE
.PP
\fB\-d\fR \fIdir\fR
.RS 4
This option specifies a directory to write the data files into\&.
.RE
.PP
\fB\-o\fR \fIfilename\fR
.RS 4
This option overrides the default
\fItrace\fR
in the
\fItrace\&.HOST:PORT\&.dat\fR
that is created when a remote host connects\&.
.RE
.PP
\fB\-l\fR \fIfilename\fR
.RS 4
This option writes the output messages to a log file instead of standard output\&.
.RE
.SH "SEE ALSO"
.sp
trace\-cmd(1), trace\-cmd\-record(1), trace\-cmd\-report(1), trace\-cmd\-start(1), trace\-cmd\-stop(1), trace\-cmd\-extract(1), trace\-cmd\-reset(1), trace\-cmd\-split(1), trace\-cmd\-list(1)
.SH "AUTHOR"
.sp
Written by Steven Rostedt, <\m[blue]\fBrostedt@goodmis\&.org\fR\m[]\&\s-2\u[1]\d\s+2>
.SH "RESOURCES"
.sp
git://git\&.kernel\&.org/pub/scm/linux/kernel/git/rostedt/trace\-cmd\&.git
.SH "COPYING"
.sp
Copyright (C) 2010 Red Hat, Inc\&. Free use of this software is granted under the terms of the GNU Public License (GPL)\&.
.SH "NOTES"
.IP " 1." 4
rostedt@goodmis.org
.RS 4
\%mailto:rostedt@goodmis.org
.RE
