'\" t
.\"     Title: trace-cmd-snapshot
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 02/03/2019
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "TRACE\-CMD\-SNAPSHOT" "1" "02/03/2019" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
trace-cmd-snapshot \- take, reset, free, or show a Ftrace kernel snapshot
.SH "SYNOPSIS"
.sp
\fBtrace\-cmd snapshot\fR [\fIOPTIONS\fR]
.SH "DESCRIPTION"
.sp
The trace\-cmd(1) snapshot controls or displays the Ftrace Linux kernel snapshot feature (if the kernel supports it)\&. This is useful to "freeze" an instance of a live trace but without stopping the trace\&.
.sp
.if n \{\
.RS 4
.\}
.nf
 trace\-cmd start \-p function
 trace\-cmd snapshot \-s
 trace\-cmd snapshot
[ dumps the content of buffer at \*(Aqtrace\-cmd snapshot \-s\*(Aq ]
 trace\-cmd snapshot \-s
 trace\-cmd snapshot
[ dumps the new content of the buffer at the last \-s operation ]
.fi
.if n \{\
.RE
.\}
.SH "OPTIONS"
.PP
\fB\-s\fR
.RS 4
Take a snapshot of the currently running buffer\&.
.RE
.PP
\fB\-r\fR
.RS 4
Clear out the buffer\&.
.RE
.PP
\fB\-f\fR
.RS 4
Free the snapshot buffer\&. The buffer takes up memory inside the kernel\&. It is best to free it when not in use\&. The first \-s operation will allocate it if it is not already allocated\&.
.RE
.PP
\fB\-c\fR \fIcpu\fR
.RS 4
Operate on a per cpu snapshot (may not be fully supported by all kernels)
.RE
.PP
\fB\-B\fR \fIbuf\fR
.RS 4
If a buffer instance was created, then the
\fB\-B\fR
option will operate on the snapshot within the buffer\&.
.RE
.SH "SEE ALSO"
.sp
trace\-cmd(1), trace\-cmd\-record(1), trace\-cmd\-report(1), trace\-cmd\-start(1), trace\-cmd\-extract(1), trace\-cmd\-reset(1), trace\-cmd\-split(1), trace\-cmd\-list(1), trace\-cmd\-listen(1)
.SH "AUTHOR"
.sp
Written by Steven Rostedt, <\m[blue]\fBrostedt@goodmis\&.org\fR\m[]\&\s-2\u[1]\d\s+2>
.SH "RESOURCES"
.sp
git://git\&.kernel\&.org/pub/scm/linux/kernel/git/rostedt/trace\-cmd\&.git
.SH "COPYING"
.sp
Copyright (C) 2010 Red Hat, Inc\&. Free use of this software is granted under the terms of the GNU Public License (GPL)\&.
.SH "NOTES"
.IP " 1." 4
rostedt@goodmis.org
.RS 4
\%mailto:rostedt@goodmis.org
.RE
