'\" t
.\"     Title: fcatch
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: April 2008
.\"    Manual: Frysk
.\"    Source: Frysk 0.4-63.fc30
.\"  Language: English
.\"
.TH "FCATCH" "1" "April 2008" "Frysk 0\&.4\-63\&.fc30" "Frysk"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
fcatch \- print a stack back\-trace of a program as it crashes
.SH "SYNOPSIS"
.HP \w'\fBfcatch\fR\ 'u
\fBfcatch\fR [\fIoptions\fR] {\fIprogram\fR\ \fIarg\fR\ ... }
.SH "DESCRIPTION"
.PP
\fBfcatch\fR
generate stack backtraces from a running application as it crashes, or upon receiving a variety of signals\&.
.SS "Stack Print Options"
.PP
\fB\-number\-of\-frames \fR\fB\fIcount\fR\fR
.RS 4
Limit the back\-trace to
\fIcount\fR
frames\&. The default is to limit the back\-trace to 10 frames\&. Specify 0 or "all" to print all frames\&.
.RE
.PP
\fB\-lite\fR
.RS 4
Perform a light\-weight stack backtrace containing only minimal information\&. Equivalent to
\fB\-print \-\fR\&.
.RE
.PP
\fB\-rich\fR
.RS 4
Perform a detailed stack back\-trace that includes, where possible, inlined function calls, parameter names and values, and debug\-names\&. Equivalent to
\fB\-print inline,params,debug\-names\fR\&.
.RE
.PP
\fB\-print \fR\fB\fIprint\-option\fR\fR\fB,\&.\&.\&.\fR
.RS 4
Specify the level of detail to include in a stack back\-trace\&.
\fIprint\-option\fR
can be any of:
.sp
debug\-names: use debug information, such as DWARF, to determine the name of functions
.sp
paths: include the full path to source files and libraries
.sp
inline: include in\-line function in back\-trace
.sp
locals: to include local variables from each frame
.sp
params: include the function parameters
.sp
To negate a
\fIprint\-option\fR
prefix it with "\-"\&.
.RE
.SS "Standard Frysk Options"
.PP
\fB\-exe\fR
.RS 4
The full path of the executable to read\&.
.RE
.PP
\fB\-noexe\fR
.RS 4
Do not attempt to read the corresponding executable when loading a core file\&.
.RE
.PP
\fB\-sysroot \fR\fB\fIdirectory\fR\fR
.RS 4
The system root directory under which all executables, libraries, and source are located\&.
.RE
.PP
\fB\-debug \fR\fB\fIclass\fR\fR\fB=\fR\fB\fIlevel\fR\fR\fB\&.\&.\&.\fR
.RS 4
Set internal debug\-tracing of the specified Java
\fIclass\fR
to
\fIlevel\fR
(level can be NONE, INFO, WARNING, FINE, and FINEST)\&. If the
\fIlevel\fR
is absent, FINE is assumed; if the
\fIclass\fR
is absent, the global level is set\&.
.RE
.SH "EXAMPLE"
.sp
.if n \{\
.RS 4
.\}
.nf
fcatch 1234
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
fcatch /usr/bin/foo
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
frysk(7)
.SH "BUGS"
.PP
Report bugs to
\m[blue]\fB\%http://sourceware.org/frysk\fR\m[]
