.TH containerd 1 01/29/2018
.SH SYNOPSIS
.PP
containerd [global options] command [command options] [arguments...]

.SH DESCRIPTION
.PP
\fBcontainerd\fP is a high performance container runtime whose daemon can be started
by using this command. If none of the \fIconfig\fP, \fIpublish\fP, or \fIhelp\fP commands
are specified the default action of the \fBcontainerd\fP command is to start the
containerd daemon in the foreground.

.PP
A default configuration is used if no TOML configuration is specified or located
at the default file location. The \fIcontainerd config\fP command can be used to
generate the default configuration for containerd. The output of that command
can be used and modified as necessary as a custom configuration.

.PP
The \fIpublish\fP command is used internally by parts of the containerd runtime
to publish events. It is not meant to be used as a standalone utility.

.SH OPTIONS
.PP
\fB\-\-config value, \-c value\fP
: Specify the default path to the configuration file (default: "/etc/containerd/config.toml")

.PP
\fB\-\-log\-level value, \-l value\fP
: Set the logging level. Available levels are: [debug, info, warn, error, fatal, panic]

.PP
\fB\-\-address value, \-a value\fP
: UNIX socket address for containerd's GRPC server to listen on (default: "/run/containerd/containerd.sock")

.PP
\fB\-\-root value\fP
: The containerd root directory (default: "/var/lib/containerd"). A persistent directory location where metadata and image content are stored

.PP
\fB\-\-state value\fP
: The containerd state directory (default: "/run/containerd"). A transient state directory used during containerd operation

.PP
\fB\-\-help, \-h\fP
: Show containerd command help text

.PP
\fB\-\-version, \-v\fP
: Print the containerd server version

.SH BUGS
.PP
Please file any specific issues that you encounter at

\[la]https://github.com/containerd/containerd\[ra]\&.

.SH AUTHOR
.PP
Phil Estes 
\[la]estesp@gmail.com\[ra]

.SH SEE ALSO
.PP
ctr(1), containerd\-config(1), containerd\-config.toml(5)
