'\" t
.\"     Title: abrt-handle-upload
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 09/24/2020
.\"    Manual: ABRT Manual
.\"    Source: abrt 2.14.4
.\"  Language: English
.\"
.TH "ABRT\-HANDLE\-UPLOAD" "1" "09/24/2020" "abrt 2\&.14\&.4" "ABRT Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
abrt-handle-upload \- Unpacks and moves problem data\&.
.SH "SYNOPSIS"
.sp
\fIabrt\-handle\-upload\fR [\-vd] ABRT_SPOOL_DIR UPLOAD_DIR FILENAME
.SH "DESCRIPTION"
.sp
The tool unpacks FILENAME located in UPLOAD_DIR and moves the problem data found in it to ABRT_SPOOL_DIR\&. It supports unpacking tarballs compressed by gzip, bzip2 or xz\&. It\(cqs called by abrtd when a new file is noticed in the upload directory configured by the \fIWatchCrashdumpArchiveDir\fR option\&.
.SH "OPTIONS"
.PP
\-v
.RS 4
Be more verbose\&. Can be given multiple times
.RE
.PP
\-d
.RS 4
Delete uploaded archive
.RE
.PP
ABRT_SPOOL_DIR
.RS 4
Directory where archives are unpacked to
.RE
.PP
UPLOAD_DIR
.RS 4
Directory where uploaded archives are stored
.RE
.PP
FILENAME
.RS 4
File name of the uploaded archive to unpack
.RE
.SH "AUTHORS"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ABRT team
.RE
.SH "SEE ALSO"
.sp
abrt\&.conf(5)
