'\" t
.\"     Title: abrtd
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 09/24/2020
.\"    Manual: ABRT Manual
.\"    Source: abrt 2.14.4
.\"  Language: English
.\"
.TH "ABRTD" "8" "09/24/2020" "abrt 2\&.14\&.4" "ABRT Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
abrtd \- automated bug reporting tool\*(Aqs daemon\&.
.SH "SYNOPSIS"
.sp
\fIabrtd\fR [\-dsv[v]\&...]
.SH "DESCRIPTION"
.sp
\fIabrtd\fR is a daemon that watches for application crashes\&. When a crash occurs, it collects the problem data (core file, application\(cqs command line etc\&.) and takes action according to the type of application that crashed and according to the configuration in the \fIabrt\&.conf\fR config file\&. There are plugins for various actions: for example to report the crash to Bugzilla, to mail the report, or to transfer the report via FTP or SCP\&. See the manual pages for the respective plugins\&.
.SH "OPTIONS"
.PP
\-v
.RS 4
Log more detailed debugging information\&.
.RE
.PP
\-d
.RS 4
Stay in the foreground and log to standard error\&.
.RE
.PP
\-s
.RS 4
Log to system log even with option \-d\&.
.RE
.PP
\-t NUM
.RS 4
Exit after NUM seconds of inactivity\&.
.RE
.PP
\-p
.RS 4
Add program names to log\&.
.RE
.SH "ENVIRONMENT"
.PP
ABRT_EVENT_NICE
.RS 4
\fIabrtd\fR
runs its post\-mortem processing with the nice value incremented by 10 in order to not take too much resources and keep the computer responsive\&. If you want to adjust the increment value, use the ABRT_EVENT_NICE environment variable\&.
.RE
.SH "CAVEATS"
.sp
When you use some other crash\-catching tool specific for an application or an application type (for example BugBuddy for GNOME applications), crashes of this type will be handled by that tool and not by \fIabrtd\fR\&. If you want \fIabrtd\fR to handle these crashes, turn off the higher\-level crash\-catching tool\&.
.SH "FILES"
.PP
/etc/abrt/abrt\&.conf
.RS 4
Configuration file for the daemon\&.
.RE
.SH "SEE ALSO"
.sp
abrt\&.conf(5)
.SH "AUTHORS"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ABRT team
.RE
