.TH tickadj 8
.SH NAME
tickadj - set time-related kernel variables
.SH \ 

.SH SYNOPSIS
\fBtickadj [ -Aqs ] [ -a \fItickadj\fB ] [ -t \fItick\fB ]\fR 

.SH DESCRIPTION

The \fBtickadj\fR program reads, and optionally modifies, several timekeeping-related variables in older kernels that do not have support for precision timekeeping, including HP-UX, SunOS, Ultrix, SGI and probably others. Those machines provide means to patch the kernel \fB/dev/kmem\fR\[char46] Newer machines with kernel time support, including Solaris, Tru64, FreeBSD and Linux, should NOT use the program, even if it appears to work, as it will destabilize the kernel time support. Use the \fBntptime\fR program instead.

The particular variables that can be changed with \fBtickadj\fR include \fBtick\fR, which is the number of microseconds added to the system time for a clock interrupt, \fBtickadj\fR, which sets the slew rate and resolution used by the \fBadjtime\fR system call, and \fBdosynctodr\fR, which indicates to the kernels on some machines whether they should internally adjust the system clock to keep it in line with time-of-day clock or not.

By default, with no arguments, \fBtickadj\fR reads the variables of interest in the kernel and displays them. At the same time, it determines an "optimal" value for the value of the \fBtickadj\fR variable if the intent is to run the \fBntpd\fR Network Time Protocol (NTP) daemon, and prints this as well. Since the operation of \fBtickadj\fR when reading the kernel mimics the operation of similar parts of the \fBntpd\fR program fairly closely, this can be useful when debugging problems with \fBntpd\fR\[char46]

Note that \fBtickadj\fR should be run with some caution when being used for the first time on different types of machines. The operations which \fBtickadj\fR tries to perform are not guaranteed to work on all Unix machines and may in rare cases cause the kernel to crash.

.SH COMMAND LINE OPTIONS

.RS 0
.TP 8
\fB-a \fItickadj\fB\fR
Set the kernel variable \fBtickadj\fR to the value \fI\fBtickadj specified.\fI\fR
.TP 8
\fB-A\fR
Set the kernel variable \fBtickadj\fR to an internally computed "optimal" value.
.TP 8
\fB-t \fItick\fB\fR
Set the kernel variable \fBtick\fR to the value \fI\fBtick\fI\fR specified.
.TP 8
\fB-s\fR
Set the kernel variable \fBdosynctodr\fR to zero, which disables the hardware time-of-year clock, a prerequisite for running the \fBntpd\fR daemon under SunOS 4.x.
.TP 8
\fB-q\fR
Normally, \fBtickadj\fR is quite verbose about what it is doing. The \fB-q\fR flag tells it to shut up about everything except errors. 
.RE

.SH FILES
\fB/vmunix /unix /dev/kmem \fR 

.SH BUGS
Fiddling with kernel variables at run time as a part of ordinary operations is a hideous practice which is only necessary to make up for deficiencies in the implementation of \fBadjtime\fR in many kernels and/or brokenness of the system clock in some vendors' kernels. It would be much better if the kernels were fixed and the \fBtickadj\fR program went away.     
.SH SEE ALSO

ntpd(8)

The official HTML documentation.

This file was automatically generated from HTML source.

