.TH containerd\-config 1 01/30/2018
.SH SYNOPSIS
.PP
containerd config [command]

.SH DESCRIPTION
.PP
The \fIcontainerd config\fP command has one subcommand, named \fIdefault\fP, which
will display on standard output the default containerd config for this version
of the containerd daemon.

.PP
This output can be piped to a \fBcontainerd\-config.toml(5)\fP file and placed in
\fB/etc/containerd\fP to be used as the configuration for containerd on daemon
startup. The configuration can be placed in any filesystem location and used
with the \fB\-\-config\fP option to the containerd daemon as well.

.PP
See \fBcontainerd\-config.toml(5)\fP for more information on the containerd
configuration options.

.SH OPTIONS
.PP
\fBdefault\fP
: This subcommand will output the TOML formatted containerd configuration to standard output

.SH BUGS
.PP
Please file any specific issues that you encounter at

\[la]https://github.com/containerd/containerd\[ra]\&.

.SH AUTHOR
.PP
Phil Estes 
\[la]estesp@gmail.com\[ra]

.SH SEE ALSO
.PP
ctr(1), containerd(1), containerd\-config.toml(5)
