.TH ctr 1 01/30/2018
.SH SYNOPSIS
.PP
\fBctr [global options] command [command options] [arguments...]\fP

.SH DESCRIPTION
.PP
\fBctr\fP is an unsupported debug and administrative client for interacting
with the containerd daemon. Because it is unsupported, the commands,
options, and operation are not guaranteed to be backward compatible or
stable from release to release of the containerd project.

.SH OPTIONS
.PP
The following commands are available in the \fBctr\fP utility:

.PP
\fBplugins,plugin\fP
: Provides information about containerd plugins

.PP
\fBversion\fP
: Prints the client and server versions

.PP
\fBcontainers,c,container\fP
: Manages and interacts with containers

.PP
\fBcontent\fP
: Manages and interacts with content

.PP
\fBevents,event\fP
: Displays containerd events

.PP
\fBimages,image\fP
: Manages and interacts with images

.PP
\fBnamespaces,namespace\fP
: Manages and interacts with containerd namespaces

.PP
\fBpprof\fP
: Provides golang pprof outputs for containerd

.PP
\fBrun\fP
: Runs a container

.PP
\fBsnapshots,snapshot\fP
: Manages and interacts with snapshots

.PP
\fBtasks,t,task\fP
: Manages and interacts with tasks

.PP
\fBshim\fP
: Interacts with a containerd shim directly

.PP
\fBhelp,h\fP
: Displays a list of commands or help for one specific command

.PP
The following global options apply to all \fBctr\fP commands:

.PP
\fB\-\-debug\fP
: Enable debug output in logs

.PP
\fB\-\-address value, \-a value\fP
: Address for containerd's GRPC server (default: \fI/run/containerd/containerd.sock\fP)

.PP
\fB\-\-timeout value\fP
: Total timeout for ctr commands (default: \fI0s\fP)

.PP
\fB\-\-connect\-timeout value\fP
: Timeout for connecting to containerd (default: \fI0s\fP)

.PP
\fB\-\-namespace value, \-n value\fP
: Namespace to use with commands (default: \fIdefault\fP) [also read from \fI$CONTAINERD\_NAMESPACE\fP]

.PP
\fB\-\-help, \-h\fP
: Show help text

.PP
\fB\-\-version, \-v\fP
: Prints the \fBctr\fP version

.SH BUGS
.PP
Note that the \fBctr\fP utility is not an officially supported part of the
containerd project releases.

.PP
However, please feel free to file any specific issues that you encounter at

\[la]https://github.com/containerd/containerd\[ra]\&.

.SH AUTHOR
.PP
Phil Estes 
\[la]estesp@gmail.com\[ra]

.SH SEE ALSO
.PP
containerd(1), containerd\-config(1), containerd\-config.toml(5)
