.TH "ETCD" "1" " etcd User Manuals" "Jan Chaloupka" "Oct 2017"  ""


.SH NAME
.PP
etcdctl \- A simple command line client for etcd


.SH SYNOPSIS
.PP
\fB[ETCDCTL_API=3] etctctl\fP [OPTIONS]


.SH DESCRIPTION
.PP
Command line client for etcd.
Queries to v2 data model are available through \fBetcdtl\fP command (see \fBetcdctl2(1)\fP).
Queries to v3 data model are available through \fBETCDCTL=3 etcdtl\fP command (see \fBetcdctl3(1)\fP).

.PP
Find more information at 
\[la]https://github.com/coreos/etcd\[ra].

.SH SEE ALSO
\fBetcd(1)\fP, \fBetcdctl2(1)\fP, \fBetcdctl3(1)\fP
