.TH "ETCD" "1" " etcd User Manuals" "Etcd contributors" "Nov 2017"  ""
.SH NAME:
etcd - Distributed reliable key-value store for the most critical data of a distributed system

.SH USAGE:
etcd [flags]

.SH DESCRIPTION:
Etcd is a distributed key-value store designed to reliably and quickly preserve and provide access to critical data. It enables reliable distributed coordination through distributed locking, leader elections, and write barriers. An etcd cluster is intended for high availability and permanent data storage and retrieval.

.SH GENERAL OPTIONS

.I Member flags

.RS
\fB--data-dir \fP
      Path to the data directory.

.RE
.RS
\fB--wal-dir \fP
      Path to the dedicated wal directory.

.RE
.RS
\fB--listen-peer-urls http://localhost:2380\fP
      List of URLs to listen on for peer traffic.

.RE
.RS
\fB--listen-client-urls http://localhost:2379\fP
      List of URLs to listen on for client traffic.

.RE
.RS
\fB--listen-metrics-urls \fP
      List of URLs to listen on for the metrics and health endpoints.

.RE
.RS
\fB--max-snapshots 5\fP
      Maximum number of snapshot files to retain (0 is unlimited).

.RE
.RS
\fB--max-wals 5\fP
      Maximum number of wal files to retain (0 is unlimited).

.RE
.RS
\fB--name default\fP
      Human-readable name for this member.

.RE
.RS
\fB--snapshot-count 100000\fP
      Number of committed transactions to trigger a snapshot to disk.

.RE
.RS
\fB--heartbeat-interval 100\fP
      Time (in milliseconds) of a heartbeat interval.

.RE
.RS
\fB--election-timeout 1000\fP
      Time (in milliseconds) for an election to timeout.

.RE
.RS
\fB--initial-election-tick-advance true\fP
      Whether to fast-forward initial election ticks on boot for faster election.

.RE
.RS
\fB--quota-backend-bytes 0\fP
      Raise alarms when backend size exceeds the given quota. 0 means use the default quota.

.RE
.RS
\fB--backend-batch-interval 0s\fP
      BackendBatchInterval is the maximum time before commit the backend transaction.

.RE
.RS
\fB--backend-batch-limit 0\fP
      BackendBatchLimit is the maximum operations before commit the backend transaction.

.RE
.RS
\fB--max-txn-ops 128\fP
      Maximum number of operations permitted in a transaction.

.RE
.RS
\fB--max-request-bytes 1572864\fP
      Maximum client request size in bytes the server will accept.

.RE
.RS
\fB--grpc-keepalive-min-time 5s\fP
      Minimum interval duration that a client should wait before pinging server.

.RE
.RS
\fB--grpc-keepalive-interval 2h0m0s\fP
      Frequency duration of server-to-client ping to check if a connection is alive (0 to disable).

.RE
.RS
\fB--grpc-keepalive-timeout 20s\fP
      Additional duration of wait before closing a non-responsive connection (0 to disable).

.RE
.I Clustering flags

.RS
\fB--initial-advertise-peer-urls http://localhost:2380\fP
      List of this member's peer URLs to advertise to the rest of the cluster.

.RE
.RS
\fB--advertise-client-urls http://localhost:2379\fP
      List of this member's client URLs to advertise to the public.

.RE
.RS
\fB--discovery \fP
      Discovery URL used to bootstrap the cluster.

.RE
.RS
\fB--discovery-fallback proxy\fP
      Valid values include ["exit" "proxy"]

.RE
.RS
\fB--discovery-proxy \fP
      HTTP proxy to use for traffic to discovery service.

.RE
.RS
\fB--discovery-srv \fP
      DNS domain used to bootstrap initial cluster.

.RE
.RS
\fB--discovery-srv-name \fP
      Service name to query when using DNS discovery.

.RE
.RS
\fB--initial-cluster default=http://localhost:2380\fP
      Initial cluster configuration for bootstrapping.

.RE
.RS
\fB--initial-cluster-token etcd-cluster\fP
      Initial cluster token for the etcd cluster during bootstrap.

.RE
.RS
\fB--initial-cluster-state new\fP
      Initial cluster state ('new' or 'existing').

.RE
.RS
\fB--strict-reconfig-check true\fP
      Reject reconfiguration requests that would cause quorum loss.

.RE
.RS
\fB--enable-v2 true\fP
      Accept etcd V2 client requests.

.RE
.RS
\fB--pre-vote false\fP
      Enable to run an additional Raft election phase.

.RE
.I Proxy flags

.RS
\fB--proxy off\fP
      Valid values include ["off" "on" "readonly"]

.RE
.RS
\fB--proxy-failure-wait 5000\fP
      Time (in milliseconds) an endpoint will be held in a failed state.

.RE
.RS
\fB--proxy-refresh-interval 30000\fP
      Time (in milliseconds) of the endpoints refresh interval.

.RE
.RS
\fB--proxy-dial-timeout 1000\fP
      Time (in milliseconds) for a dial to timeout.

.RE
.RS
\fB--proxy-write-timeout 5000\fP
      Time (in milliseconds) for a write to timeout.

.RE
.RS
\fB--proxy-read-timeout 0\fP
      Time (in milliseconds) for a read to timeout.

.RE
.I Security flags

.RS
\fB--cert-file \fP
      Path to the client server TLS cert file.

.RE
.RS
\fB--key-file \fP
      Path to the client server TLS key file.

.RE
.RS
\fB--client-cert-auth false\fP
      Enable client cert authentication.

.RE
.RS
\fB--client-crl-file \fP
      Path to the client certificate revocation list file.

.RE
.RS
\fB--trusted-ca-file \fP
      Path to the client server TLS trusted CA cert file.

.RE
.RS
\fB--auto-tls false\fP
      Client TLS using generated certificates

.RE
.RS
\fB--peer-cert-file \fP
      Path to the peer server TLS cert file.

.RE
.RS
\fB--peer-key-file \fP
      Path to the peer server TLS key file.

.RE
.RS
\fB--peer-client-cert-auth false\fP
      Enable peer client cert authentication.

.RE
.RS
\fB--peer-trusted-ca-file \fP
      Path to the peer server TLS trusted CA file.

.RE
.RS
\fB--peer-auto-tls false\fP
      Peer TLS using generated certificates

.RE
.RS
\fB--peer-crl-file \fP
      Path to the peer certificate revocation list file.

.RE
.RS
\fB--peer-cert-allowed-cn \fP
      Allowed CN for inter peer authentication.

.RE
.RS
\fB--cipher-suites \fP
      Comma-separated list of supported TLS cipher suites between client/server and peers (empty will be auto-populated by Go).

.RE
.RS
\fB--cors *\fP
      Comma-separated white list of origins for CORS, or cross-origin resource sharing, (empty or * means allow all)

.RE
.RS
\fB--host-whitelist *\fP
      Comma-separated acceptable hostnames from HTTP client requests, if server is not secure (empty means allow all).

.RE
.I Logging flags

.RS
\fB--logger capnslog\fP
      Specify 'zap' for structured logging or 'capnslog'.

.RE
.RS
\fB--log-output default\fP
      DEPRECATED: use '--log-outputs'.

.RE
.RS
\fB--log-outputs default\fP
      Specify 'stdout' or 'stderr' to skip journald logging even when running under systemd, or list of comma separated output targets.

.RE
.RS
\fB--debug false\fP
      Enable debug-level logging for etcd.

.RE
.RS
\fB--log-package-levels \fP
      (To be deprecated) Specify a particular log level for each etcd package (eg: 'etcdmain=CRITICAL,etcdserver=DEBUG').

.RE
.I Version flags

.RS
\fB--version false\fP
      Print the version and exit.

.RE
.RS
\fB--auto-compaction-retention 0\fP
      Auto compaction retention for mvcc key value store. 0 means disable auto compaction.

.RE
.RS
\fB--auto-compaction-mode periodic\fP
      interpret 'auto-compaction-retention' one of: periodic|revision. 'periodic' for duration based retention, defaulting to hours if no time unit is provided (e.g. '5m'). 'revision' for revision number based retention.

.RE
.I Profiling flags

.RS
\fB--enable-pprof false\fP
      Enable runtime profiling data via HTTP server. Address is at client URL + "/debug/pprof/"

.RE
.RS
\fB--metrics basic\fP
      Set level of detail for exported metrics, specify 'extensive' to include histogram metrics

.RE
.I Auth flags

.RS
\fB--auth-token simple\fP
      Specify auth token specific options.

.RE
.RS
\fB--bcrypt-cost 10\fP
      Specify bcrypt algorithm cost factor for auth password hashing.

.RE
.I Gateway flags

.RS
\fB--enable-grpc-gateway true\fP
      Enable GRPC gateway.

.RE
.I Experimental flags

.RS
\fB--experimental-initial-corrupt-check false\fP
      Enable to check data corruption before serving any client/peer traffic.

.RE
.RS
\fB--experimental-corrupt-check-time 0s\fP
      Duration of time between cluster corruption check passes.

.RE
.RS
\fB--experimental-enable-v2v3 \fP
      v3 prefix for serving emulated v2 state.

.RE
.RS
\fB--experimental-backend-bbolt-freelist-type \fP
      ExperimentalBackendFreelistType specifies the type of freelist that boltdb backend uses(array and map are supported types)

.RE
.I Unsafe flags

.RS
\fB--force-new-cluster false\fP
      Force to create a new one member cluster.

.RE
.SH SEE ALSO:
\fBetcdctl(1)\fP, \fBetcdctl2(1)\fP, \fBetcdctl3(1)\fP

